### ISSUE TITLE
unsupported operand type(s) for +: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by mrmrn** [arnab64/textclusteringDBSCAN#1]
hi,
I used the code, every step runs ok but the final step gave me this error:
```
marn@mint18 ~/c/t/textclusteringDBSCAN> python 6_main_module.py
Traceback (most recent call last):
  File "6_main_module.py", line 38, in <module>
    init_threshold = find_near_threshold()	
  File "6_main_module.py", line 32, in find_near_threshold
    scorex = scorex + scr
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

how to get rid of this error?

**Comment by dsjijo** [comment]
Even I got the error when I used different source files. I this file at the line 12 u need to give the no of files and at line 7 u need to give correct clustering of current source.
hope it works!
